version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "skip issue"
      - "skip news"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    cooldown:
      default-days: 14

  - package-ecosystem: "pip"
    directory: "/Tools/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "skip issue"
      - "skip news"
    cooldown:
      default-days: 14
